name: $(BuildDefinitionName)_$(date:yyyyMMdd)_$(rev:.r)

# trigger:
#   branches:
#     include: ["main"]

# pr:
#   autoCancel: false
#   branches:
#     include: ["*"]

pool:
  vmImage: $(vmImageName)

variables:
  - template: ./.ci/pipeline-variables.yml

stages:
  # Linting
  - template: ./.ci/stage-static-analysis.yml
    parameters:
      srcFolder: $(srcFolder)
      testResultsPath: $(testResultsPath)
      vmImage: $(vmImage)

  # Unit Tests
  # Integration Tests
    # Import
    # Test outputs with pester
  # Build
    # Version bump
    # Minify and Package
    # Artifact
  # Publish
