name: $(BuildDefinitionName)_$(date:yyyyMMdd)_$(rev:.r)

trigger:
  branches:
    include: ["main"]

pr:
  autoCancel: false
  branches:
    include: ["*"]

variables:
  - template: .ci/variables/pipeline-variables.yml

stages:
  # Linting
  - template: .ci/stages/stage-static-analysis.yml
    parameters:
      srcFolder: $(srcFolder)
      testResultsPath: $(testResultsPath)
      vmImage: $(vmLinuxImage)
      megaLinterFlavour: $(megaLinterFlavour)
      megaLinterVersion: $(megaLinterVersion)
      secretlintVersion: $(secretlintVersion)

  # Unit Tests
  - template: .ci/stages/stage-unit-tests.yml
    parameters:
      dependencyConfigPath: $(dependencyConfigPath)
      psakeFilePath: $(psakeFilePath)
      testResultsPath: $(testResultsPath)
      unitTestsFolder: $(unitTestsFolder)
      entryScriptPath: $(entryScriptPath)
      vmLinuxImage: $(vmLinuxImage)
      vmMacosImage: $(vmMacosImage)
      vmWindowsImage: $(vmWindowsImage)

  # Integration Tests
  - template: .ci/stages/stage-integration-tests.yml
    parameters:
      dependencyConfigPath: $(dependencyConfigPath)
      integrationTestsFolder: $(integrationTestsFolder)
      psakeFilePath: $(psakeFilePath)
      testResultsPath: $(testResultsPath)
      entryScriptPath: $(entryScriptPath)
      vmLinuxImage: $(vmLinuxImage)
      vmMacosImage: $(vmMacosImage)
      vmWindowsImage: $(vmWindowsImage)

  # Build & Deploy
  - template: .ci/stages/stage-build-deploy.yml
    parameters:
      vmLinuxImage: $(vmLinuxImage)
      entryScriptPath: $(entryScriptPath)
      dependencyConfigPath: $(dependencyConfigPath)
      psakeFilePath: $(psakeFilePath)
      docsFolder: $(docsFolder)
