name: $(BuildDefinitionName)_$(date:yyyyMMdd)_$(rev:.r)

trigger:
  branches:
    include: ["main"]

pr:
  autoCancel: false
  branches:
    include: ["*"]

variables:
  - template: ./.ci/pipeline-variables.yml

stages:
  # Linting
  - template: ./.ci/stage-static-analysis.yml
    parameters:
      srcFolder: $(srcFolder)
      testResultsPath: $(testResultsPath)
      vmImage: $(vmLinuxImage)
      megaLinterFlavour: $(megaLinterFlavour)
      megaLinterVersion: $(megaLinterVersion)
      secretlintVersion: $(secretlintVersion)

  # Unit Tests
  - template: ./.ci/stage-unit-tests.yml
    parameters:
      buildFolder: $(buildFolder)
      testResultsPath: $(testResultsPath)
      vmLinuxImage: $(vmLinuxImage)
      vmMacosImage: $(vmMacosImage)
      vmWindowsImage: $(vmWindowsImage)

  # Integration Tests
  - template: ./.ci/stage-integration-tests.yml
    parameters:
      buildFolder: $(buildFolder)
      testResultsPath: $(testResultsPath)
      vmLinuxImage: $(vmLinuxImage)
      vmMacosImage: $(vmMacosImage)
      vmWindowsImage: $(vmWindowsImage)

  # Build
  - template: ./.ci/stage-build.yml
    parameters:
      vmLinuxImage: $(vmLinuxImage)

  # Publish
