parameters:
  - name: buildFolder
    type: string
  - name: testResultsPath
    type: string
  - name: vmLinuxImage
    type: string
  - name: vmMacosImage
    type: string
  - name: vmWindowsImage
    type: string

stages:
  - stage: unitTests
    displayName: Unit Tests
    dependsOn: [staticAnalysis]
    condition: |
      and(
        succeeded(),
        ne(variables['Build.SourceBranch'], 'refs/heads/main')
      )
    jobs:
      - job: linuxUnitTests
        displayName: "Linux Tests"
        pool:
          vmImage: $(vmLinuxImage)
        steps:
          - template: ./step.unit-tests.yml
            parameters:
              operatingSystem: Linux
              testResultsPath: ${{ parameters.testResultsPath }}

      - job: macosUnitTests
        displayName: "MacOS Tests"
        pool:
          vmImage: $(vmMacosImage)
        steps:
          - template: ./step.unit-tests.yml
            parameters:
              operatingSystem: macOS
              testResultsPath: ${{ parameters.testResultsPath }}

      - job: windowsUnitTests
        displayName: "Windows Tests"
        pool:
          vmImage: $(vmWindowsImage)
        steps:
          - template: ./step.unit-tests.yml
            parameters:
              operatingSystem: Windows
              testResultsPath: ${{ parameters.testResultsPath }}
