parameters:
  - name: buildFolder
    type: string
  - name: vmLinuxImage
    type: string
  - name: testResultsPath
    type: string

stages:
  - stage: unitTests
    displayName: Unit Tests
    dependsOn: [staticAnalysis]
    condition: succeeded()
    jobs:
      - job: linuxUnitTests
        displayName: "Linux Tests"
        pool:
          vmImage: $(vmLinuxImage)
        steps:
          - template: ./step.unit-tests.yml
            parameters:
              operatingSystem: Linux
              testResultsPath: ${{ parameters.testResultsPath }}
