parameters:
  - name: dependencyConfigPath
    type: string
  - name: integrationTestsFolder
    type: string
  - name: psakeFilePath
    type: string
  - name: testResultsPath
    type: string
  - name: utilScriptPath
    type: string
  - name: vmLinuxImage
    type: string
  - name: vmMacosImage
    type: string
  - name: vmWindowsImage
    type: string

stages:
  - stage: integrationTests
    displayName: Integration Tests
    dependsOn: [unitTests]
    condition: |
      and(
        succeeded(),
        ne(variables['Build.SourceBranch'], 'refs/heads/main')
      )
    jobs:
      - job: linuxUnitTests
        displayName: "Linux"
        pool:
          vmImage: $(vmLinuxImage)
        steps:
          - template: ./step.integration-tests.yml
            parameters:
              operatingSystem: Linux
              dependencyConfigPath: ${{ parameters.dependencyConfigPath }}
              integrationTestsFolder: ${{ parameters.integrationTestsFolder}}
              psakeFilePath: ${{ parameters.psakeFilePath }}
              testResultsPath: ${{ parameters.testResultsPath }}
              utilScriptPath: ${{ parameters.utilScriptPath }}

      - job: macosUnitTests
        displayName: "MacOS"
        pool:
          vmImage: $(vmMacosImage)
        steps:
          - template: ./step.integration-tests.yml
            parameters:
              operatingSystem: macOS
              utilScriptPath: ${{ parameters.utilScriptPath }}
              dependencyConfigPath: ${{ parameters.dependencyConfigPath }}
              psakeFilePath: ${{ parameters.psakeFilePath }}
              integrationTestsFolder: ${{ parameters.integrationTestsFolder}}
              testResultsPath: ${{ parameters.testResultsPath }}

      - job: windowsUnitTests
        displayName: "Windows"
        pool:
          vmImage: $(vmWindowsImage)
        steps:
          - template: ./step.integration-tests.yml
            parameters:
              operatingSystem: Windows
              utilScriptPath: ${{ parameters.utilScriptPath }}
              dependencyConfigPath: ${{ parameters.dependencyConfigPath }}
              psakeFilePath: ${{ parameters.psakeFilePath }}
              testResultsPath: ${{ parameters.testResultsPath }}
              integrationTestsFolder: ${{ parameters.integrationTestsFolder}}
              integrationTestsFolder: ${{ parameters.integrationTestsFolder}}
