parameters:
  - name: dependencyConfigPath
    type: string
  - name: psakeFilePath
    type: string
  - name: testResultsPath
    type: string
  - name: unitTestsFolder
    type: string
  - name: utilScriptPath
    type: string
  - name: vmLinuxImage
    type: string
  - name: vmMacosImage
    type: string
  - name: vmWindowsImage
    type: string

stages:
  - stage: unitTests
    displayName: Unit Tests
    dependsOn: [staticAnalysis]
    condition: |
      and(
        succeeded(),
        ne(variables['Build.SourceBranch'], 'refs/heads/main')
      )
    jobs:
      - job: linuxUnitTests
        displayName: "Linux Tests"
        pool:
          vmImage: $(vmLinuxImage)
        steps:
          - template: ../steps/step.unit-tests.yml
            parameters:
              operatingSystem: Linux
              dependencyConfigPath: ${{ parameters.dependencyConfigPath }}
              psakeFilePath: ${{ parameters.psakeFilePath }}
              testResultsPath: ${{ parameters.testResultsPath }}
              unitTestsFolder: ${{ parameters.unitTestsFolder}}
              utilScriptPath: ${{ parameters.utilScriptPath }}

      - job: macosUnitTests
        displayName: "MacOS Tests"
        pool:
          vmImage: $(vmMacosImage)
        steps:
          - template: ../steps/step.unit-tests.yml
            parameters:
              operatingSystem: macOS
              dependencyConfigPath: ${{ parameters.dependencyConfigPath }}
              psakeFilePath: ${{ parameters.psakeFilePath }}
              testResultsPath: ${{ parameters.testResultsPath }}
              unitTestsFolder: ${{ parameters.unitTestsFolder}}
              utilScriptPath: ${{ parameters.utilScriptPath }}

      - job: windowsUnitTests
        displayName: "Windows Tests"
        pool:
          vmImage: $(vmWindowsImage)
        steps:
          - template: ../steps/step.unit-tests.yml
            parameters:
              operatingSystem: Windows
              dependencyConfigPath: ${{ parameters.dependencyConfigPath }}
              psakeFilePath: ${{ parameters.psakeFilePath }}
              testResultsPath: ${{ parameters.testResultsPath }}
              unitTestsFolder: ${{ parameters.unitTestsFolder}}
              utilScriptPath: ${{ parameters.utilScriptPath }}
